modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/BiggerGreen/InsanityCraft/issues"

[[mods]]
modId="insanityoverworld"
version="${file.jarVersion}"
displayName="InsanityCraft Overworld"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/insanitycraft"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

credits="Thanks for InsanityCraft goes to Link, Dargon, and Targren! Without you guys, this dream would've never come true. Also, thanks to TheyCallMeDanger for writing OreSpawn, the inspiration for this mod!" #optional
authors="BiggerGreen, Lord_Dargon, Targren, Corrupted_Link."
description='''
A rootin', tootin', big boss shootin' adventure of EPIC PROPORTIONS!

Inspired by TheyCallMeDanger's OreSpawn mod.
'''

[[dependencies.insanityoverworld]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.insanityoverworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
